/* Saved adventures: all clocks use elapsed time and all listeners leave with the game. */
const AdventureSave={
 read(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v&&typeof v==='object'?v:fallback;}catch{return fallback;}},
 write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}},
 number(v,min,max,fallback=0){return typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max?v:fallback;}
};
function expeditionCamp(){
 const KEY='shelf-camp-v1',raw=AdventureSave.read(KEY,{}),num=AdventureSave.number;
 let s={coins:num(raw.coins,0,1e12),power:Math.floor(num(raw.power,1,100,1)),helpers:Math.floor(num(raw.helpers,0,100)),region:Math.floor(num(raw.region,0,2)),taps:Math.floor(num(raw.taps,0,1e9)),trips:Math.floor(num(raw.trips,0,1e6)),quests:Array.isArray(raw.quests)?raw.quests.filter(i=>Number.isInteger(i)&&i>=0&&i<4):[],stamp:Date.now(),trip:null};
 if(raw.trip&&Number.isFinite(raw.trip.end)&&raw.trip.end>0&&raw.trip.end<=Date.now()+180000&&Number.isInteger(raw.trip.region)&&raw.trip.region>=0&&raw.trip.region<=s.region)s.trip={end:raw.trip.end,region:raw.trip.region};
 const places=[{name:'Whispering forest',icon:'🌲',cost:40,time:30,reward:85},{name:'Crystal caverns',icon:'💎',cost:180,time:60,reward:390},{name:'Floating ruins',icon:'🏛️',cost:600,time:90,reward:1350}];
 const income=()=>s.helpers*(1+s.region),offline=Math.min(14400,Math.max(0,(Date.now()-num(raw.stamp,0,Date.now(),Date.now()))/1000)),earned=Math.floor(offline*income());s.coins=Math.min(1e12,s.coins+earned);
 let notice=earned?`Welcome back! Your helpers earned ${earned.toLocaleString()} coins over ${Math.floor(offline/60)} minutes (up to 4 hours).`:raw.stamp?'Welcome back to your camp. Choose your next upgrade or expedition.':'Your expedition begins with a single coin.',last=Date.now(),bonusAt=Date.now()+45000,bonus=false,session=GameRuns.session('clicker'),sessionTaps=0,sessionDay=DailyChallenges.dayKey();
 shell('Clicker Adventure','Build a camp, gather a crew, and explore three destinations.',`<div class="panel adventure"><div id="camp-scene" class="camp-scene"></div><div id="camp-stats" class="stats"></div><p id="camp-note" role="status"></p><button id="coin" class="camp-coin" aria-label="Gather coins">🪙</button><button id="camp-bonus" hidden>Open travelling merchant’s gift · +50 coins</button><div class="adventure-grid"><section><h3>Grow your camp</h3><button id="upgrade"></button><button id="helper"></button><button id="region"></button></section><section><h3>Expeditions</h3><p id="trip-description"></p><button id="trip"></button><p>Helpers keep earning while you explore.</p></section><section><h3>Camp journal</h3><div id="quests"></div></section></div><p id="camp-storage" class="muted"></p><details><summary>Start over</summary><p>This clears this camp only.</p><button id="camp-reset">Reset camp progress</button></details></div>`);
 const $=id=>document.getElementById(id),tapCost=()=>Math.ceil(15*1.8**(s.power-1)),helperCost=()=>Math.ceil(35*1.55**s.helpers);
 const quests=[{title:'Gather 25 times',done:()=>s.taps>=25,reward:50},{title:'Hire 3 helpers',done:()=>s.helpers>=3,reward:100},{title:'Return from 3 expeditions',done:()=>s.trips>=3,reward:200},{title:'Discover the floating ruins',done:()=>s.region===2,reward:500}];
 function save(){s.stamp=Date.now();$('camp-storage').textContent=AdventureSave.write(KEY,s)?'Progress saved automatically on this browser.':'Storage unavailable — progress lasts for this visit only.';}
 function render(){const p=places[s.region];$('camp-scene').textContent=`${p.icon} ${s.helpers?'🏕️':'⛺'} ${s.helpers>=3?'🔥 🛖':''} ${s.helpers>=6?'🏠 🏠':''} ${s.region===2?'🎈':''}`;$('camp-stats').textContent=`${Math.floor(s.coins).toLocaleString()} coins · ${s.power} per tap · ${income()} per second`;$('camp-note').textContent=notice;
 $('upgrade').textContent=s.power===100?'Tap power mastered':`Upgrade tap to ${s.power+1} · ${tapCost()} coins`;$('upgrade').disabled=s.power>=100||s.coins<tapCost();$('helper').textContent=`Hire helper (${s.helpers}) · ${helperCost()} coins`;$('helper').disabled=s.helpers>=100||s.coins<helperCost();const rc=s.region===0?500:2500;$('region').textContent=s.region===2?'All destinations discovered':`Discover ${places[s.region+1].name} · ${rc} coins`;$('region').disabled=s.region===2||s.coins<rc;
 $('trip-description').textContent=`${p.name}: ${p.time} seconds, ${p.cost} coins to depart, ${p.reward} coins on return.`;$('trip').textContent=s.trip?`Exploring ${places[s.trip.region].name} · ${Math.max(0,Math.ceil((s.trip.end-Date.now())/1000))}s`:'Send expedition';$('trip').disabled=!!s.trip||s.coins<p.cost;
 $('camp-bonus').hidden=!bonus;quests.forEach((q,i)=>{let b=$('quests').children[i];if(!b){b=document.createElement('button');$('quests').append(b);}b.textContent=`${s.quests.includes(i)?'✓':q.done()?'Claim':'○'} ${q.title} · ${q.reward} coins`;b.disabled=s.quests.includes(i)||!q.done();b.onclick=()=>{if(!q.done()||s.quests.includes(i))return;s.quests.push(i);s.coins+=q.reward;notice=`Journal reward: ${q.reward} coins.`;save();render();};});}
 function settle(){const now=Date.now();s.coins=Math.min(1e12,s.coins+Math.min(14400,Math.max(0,(now-last)/1000))*income());last=now;if(s.trip&&now>=s.trip.end){s.coins+=places[s.trip.region].reward;s.trips++;s.trip=null;notice='Your expedition returned with treasure!';}if(now>=bonusAt&&!document.hidden)bonus=true;}
 $('coin').onclick=()=>{settle();if(sessionDay!==DailyChallenges.dayKey()){session.reset();sessionTaps=0;sessionDay=DailyChallenges.dayKey();}session.start('camp');s.coins=Math.min(1e12,s.coins+s.power);s.taps++;sessionTaps++;session.progress({taps:sessionTaps});if(!matchMedia('(prefers-reduced-motion: reduce)').matches){$('coin').animate?.([{transform:'scale(.92)'},{transform:'scale(1)'}],{duration:130});const gain=document.createElement('span');gain.className='camp-gain';gain.textContent=`+${s.power}`;$('coin').append(gain);gain.addEventListener('animationend',()=>gain.remove(),{once:true});}save();render();};
 $('upgrade').onclick=()=>{settle();if(s.power>=100||s.coins<tapCost())return;s.coins-=tapCost();s.power++;Shelf.record('clicker_power',{power:s.power});save();render();};
 $('helper').onclick=()=>{settle();if(s.helpers>=100||s.coins<helperCost())return;s.coins-=helperCost();s.helpers++;save();render();};
 $('region').onclick=()=>{settle();const cost=s.region===0?500:2500;if(s.region===2||s.coins<cost)return;s.coins-=cost;s.region++;notice=`Discovered ${places[s.region].name}! Each helper now earns ${1+s.region} coins per second.`;save();render();};
 $('trip').onclick=()=>{settle();const p=places[s.region];if(s.trip||s.coins<p.cost)return;s.coins-=p.cost;s.trip={region:s.region,end:Date.now()+p.time*1000};save();render();};
 $('camp-bonus').onclick=()=>{if(!bonus)return;s.coins+=50;bonus=false;bonusAt=Date.now()+60000;notice='A travelling merchant left 50 coins for your camp.';save();render();};
 $('camp-reset').onclick=()=>{if(!confirm('Reset your camp, coins and expedition progress?'))return;AdventureSave.write(KEY,{});clearInterval(timer);session.dispose();removeEventListener('pagehide',leaving);clean=()=>{};expeditionCamp();};
 const timer=setInterval(()=>{settle();save();render();},1000);const leaving=()=>{settle();save();};addEventListener('pagehide',leaving);clean=()=>{leaving();clearInterval(timer);session.dispose();removeEventListener('pagehide',leaving);};settle();save();render();
}
function trailPlatformer(){
 const KEY='shelf-platform-v1',raw=AdventureSave.read(KEY,{}),worlds=['Sunlit meadow','Lantern caverns','Cloud rooftops'],names=['First steps','Spring picnic','Across the brook','Meadow lookout','Stone steps','Moving lanterns','Crumbling bridge','Cavern crossing','Roof garden','High wire','Skyward springs','The final climb'];
 const saved={levels:Array.from({length:12},(_,i)=>{const r=raw.levels?.[i];return {done:r?.done===true,stars:[0,1,2].filter(n=>Array.isArray(r?.stars)&&r.stars.includes(n)),best:AdventureSave.number(r?.best,0.01,1e6,null)};})};
 // A level unlock must follow a completed path; malformed saves cannot unlock an isolated world.
 for(let i=1;i<12;i++)if(!saved.levels[i-1].done)saved.levels[i]={done:false,stars:[],best:null};
 let level=0,raf=0,last=0,acc=0,p=null,platforms=[],stars=[],enemies=[],checkpoint=40,checkpointOn=false,elapsed=0,deaths=0,won=false,paused=false,playing=false,keys=new Set(),pointers=new Map(),jumpWas=false,buffer=0,coyote=0,camera=0,session=null,collected=new Set(),active=true;
 const W=640,H=360,end=1510,ground=310,overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
 shell('Mini Platformer','A twelve-stop journey. Move with ← → or A/D; hold Space to jump higher.',`<div class="panel adventure"><div id="trail-map" class="trail-map"></div><section id="trail-stage" hidden><div id="trail-stats" class="stats"></div><canvas id="trail-canvas" class="canvas" width="640" height="360" tabindex="0" aria-label="Platformer course. Arrow keys to move, Space to jump. Reach the flag and collect three stars."></canvas><p id="platform-note" role="status"></p><div class="controls"><button data-p="left" aria-label="Move left">←</button><button data-p="jump">Jump</button><button data-p="right" aria-label="Move right">→</button><button id="trail-pause">Pause</button><button id="trail-restart">Restart level</button><button id="trail-back">Level map</button><button id="trail-next" hidden>Next level</button></div></section><p id="trail-storage"></p></div>`);
 const $=id=>document.getElementById(id),canvas=$('trail-canvas'),ctx=canvas.getContext('2d');
 function save(){$('trail-storage').textContent=AdventureSave.write(KEY,saved)?'Level unlocks, stars and best times save on this browser.':'Storage unavailable — progress lasts for this visit only.';}
 function release(){keys.clear();pointers.clear();buffer=0;jumpWas=false;}
 function map(){playing=false;session?.dispose();release();$('trail-stage').hidden=true;$('trail-map').hidden=false;$('trail-map').replaceChildren(...worlds.map((name,w)=>{const section=document.createElement('section');const h=document.createElement('h3');h.textContent=name;section.append(h);for(let j=0;j<4;j++){const i=w*4+j,r=saved.levels[i],b=document.createElement('button');b.dataset.level=i;b.disabled=i>0&&!saved.levels[i-1].done;b.textContent=`${i+1}. ${names[i]} · ${r.stars.length}/3 ★${r.best?` · ${r.best.toFixed(1)}s`:''}${b.disabled?' · Locked':''}`;b.onclick=()=>start(i);section.append(b);}return section;}));}
 function build(i){const world=Math.floor(i/4),variant=i%4;
 platforms=[{x:0,y:ground,w:330,h:50},{x:440,y:ground,w:330,h:50},{x:870,y:ground,w:300,h:50},{x:1280,y:ground,w:340,h:50},
 {x:180,y:248,w:85,h:14},{x:260,y:170,w:92,h:14},{x:370,y:264,w:70,h:14},
 {x:550,y:248,w:90,h:14},{x:660,y:170,w:90,h:14},{x:800,y:268,w:70,h:14},
 {x:970,y:248,w:90,h:14},{x:1080,y:170,w:90,h:14},{x:1210,y:265,w:75,h:14}].map((a,n)=>({...a,id:n,baseX:a.x,baseY:a.y,type:'solid',touched:0,gone:0}));
 if(i>=1)platforms[4].type='spring';
 if(world>=1){platforms[7].type='moving';platforms[7].range=35;platforms[8].type=variant>=2?'crumble':'solid';platforms[11].type='crumble';}
 if(world===2){platforms[10].type='spring';platforms[5].type='moving';platforms[5].range=25;}
 // Each stop changes its gaps and upper route while keeping jumps within reach.
 const shift=variant*12+world*7,second=variant*9;platforms[4].x-=shift;platforms[4].baseX-=shift;platforms[0].w-=shift;platforms[1].x-=shift;platforms[1].baseX-=shift;platforms[1].w+=shift-second;platforms[2].x-=second;platforms[2].baseX-=second;platforms[2].w+=second;platforms[6].x-=shift;platforms[6].baseX-=shift;platforms[9].x-=second;platforms[9].baseX-=second;platforms[3].x+=variant*6;platforms[3].w-=variant*6;platforms[12].x+=variant*3;platforms[12].baseX+=variant*3;
 if(world>=1&&variant>=1){platforms[6].type='moving';platforms[6].range=12;}
 if(world>=1&&variant>=2)platforms[9].type='crumble';
 platforms[7].y-=variant*7;platforms[7].baseY=platforms[7].y;
 stars=[{x:220-shift,y:218},{x:595,y:218-variant*7},{x:1010,y:218}];
 enemies=i>=2?[{x:560,y:290,w:24,h:20,base:560,range:75,speed:1+variant*.2,dead:false}]:[];
 if(world>=1)enemies.push({x:1000,y:290,w:24,h:20,base:1000,range:70,speed:1.3,dead:false});
 }
 function spawn(){p={x:checkpoint,y:280,w:22,h:30,vx:0,vy:0,on:null};coyote=0;buffer=0;release();}
 function start(i){sessionStarted=false;level=i;session?.dispose();session=GameRuns.session('platform');elapsed=0;deaths=0;checkpoint=40;checkpointOn=false;won=false;paused=false;playing=true;collected=new Set();build(i);spawn();$('trail-map').hidden=true;$('trail-stage').hidden=false;$('trail-next').hidden=true;$('trail-pause').textContent='Pause';$('platform-note').textContent=i===0?'Jump across gaps. Small ledges lead to optional stars. The orange pennant is a checkpoint.':'Gold pads bounce you up; blue platforms move; cracked platforms fall. Jump on creatures to clear them.';canvas.focus();last=0;acc=0;draw();}
 function pause(){if(!playing||won)return;paused=!paused;release();$('trail-pause').textContent=paused?'Resume':'Pause';$('platform-note').textContent=paused?'Paused. Resume when ready.':'Onward to the flag!';if(paused)session.pause();else{session.resume();canvas.focus();}}
 function finish(){if(won)return;won=true;release();const r=saved.levels[level];r.done=true;r.stars=[...new Set([...r.stars,...collected])].sort();r.best=r.best===null?elapsed:Math.min(r.best,elapsed);save();Shelf.record('platform_win',{});session.finish({level:level+1,stars:collected.size,complete:true});$('platform-note').textContent=`Level complete! ${collected.size}/3 stars · ${elapsed.toFixed(1)}s · ${deaths} retries.${level===11?' You completed all three worlds!':''}`;$('trail-next').hidden=level===11;}
 function step(dt){if(!playing||paused||won)return;const held=k=>keys.has(k)||[...pointers.values()].includes(k),moving=held('left')||held('right')||held('jump');if(moving)session.start('trail');if(!sessionStarted&&moving)sessionStarted=true;if(!sessionStarted)return;elapsed+=dt;
 const jump=held('jump');if(jump&&!jumpWas)buffer=.12;else buffer=Math.max(0,buffer-dt);if(!jump&&jumpWas&&p.vy< -180)p.vy=-180;jumpWas=jump;coyote=p.on!==null?.1:Math.max(0,coyote-dt);
 if(buffer>0&&coyote>0){p.vy=-440;p.on=null;buffer=0;coyote=0;}
 const target=(held('right')?220:0)-(held('left')?220:0);p.vx+=Math.max(-1500*dt,Math.min(1500*dt,target-p.vx));
 for(const q of platforms){const old=q.x;if(q.type==='moving')q.x=q.baseX+Math.sin(elapsed*1.6)*q.range;if(p.on===q.id)p.x+=q.x-old;if(q.gone>0){q.gone=Math.max(0,q.gone-dt);if(!q.gone)q.touched=0;}else if(q.touched>0){q.touched+=dt;if(q.touched>.6){q.gone=2.5;if(p.on===q.id)p.on=null;}}}
 p.x=Math.max(0,Math.min(end+50,p.x+p.vx*dt));for(const q of platforms)if(!q.gone&&overlap(p,q)){if(p.vx>0)p.x=q.x-p.w;else if(p.vx<0)p.x=q.x+q.w;p.vx=0;}
 const oldY=p.y;p.vy=Math.min(650,p.vy+1100*dt);p.y+=p.vy*dt;p.on=null;
 for(const q of platforms)if(!q.gone&&overlap(p,q)){if(p.vy>=0&&oldY+p.h<=q.y+2){p.y=q.y-p.h;p.vy=0;p.on=q.id;if(q.type==='spring'){p.vy=-570;p.on=null;}if(q.type==='crumble'&&!q.touched)q.touched=dt;}else if(p.vy<0&&oldY>=q.y+q.h-2){p.y=q.y+q.h;p.vy=0;}}
 for(let i=0;i<stars.length;i++){const a=stars[i];if(overlap(p,{x:a.x-11,y:a.y-11,w:22,h:22}))collected.add(i);}
 if(p.x>680&&p.x<770&&p.y+p.h>=280&&!checkpointOn){checkpoint=690;checkpointOn=true;$('platform-note').textContent='Checkpoint saved for this attempt!';}
 for(const e of enemies){if(e.dead)continue;e.x=e.base+Math.sin(elapsed*e.speed)*e.range;if(overlap(p,e)){if(p.vy>0&&oldY+p.h<=e.y+7){e.dead=true;p.vy=-300;}else{deaths++;spawn();return;}}}
 if(p.y>H+60){deaths++;spawn();$('platform-note').textContent='Try again — your collected stars stay with you.';return;}
 if(p.x>=end&&p.y+p.h>270)finish();
 }
 let sessionStarted=false;
 function draw(){if(!playing)return;camera=Math.max(0,Math.min(980,p.x-200));const world=Math.floor(level/4);ctx.fillStyle=['#d5f0ed','#252b49','#e6def5'][world];ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(-camera,0);ctx.fillStyle=['#b1d9ca','#353e60','#c9bbdf'][world];for(let i=0;i<9;i++){ctx.beginPath();ctx.arc(i*230+80,330,140,Math.PI,0);ctx.fill();}
 for(const q of platforms){if(q.gone)continue;ctx.fillStyle=q.type==='spring'?'#e8b348':q.type==='moving'?'#5395ba':q.type==='crumble'?'#a98572':['#548d70','#777799','#9281ab'][world];ctx.fillRect(q.x,q.y,q.w,q.h);ctx.fillStyle='#ffffff55';ctx.fillRect(q.x,q.y,q.w,4);if(q.type==='crumble'){ctx.fillStyle='#483b43';ctx.fillText('╱╲╱╲',q.x+15,q.y+12);}if(q.type==='spring'){ctx.fillStyle='#523b26';ctx.fillText('↑ ↑',q.x+25,q.y+12);}}
 ctx.font='23px sans-serif';stars.forEach((s,i)=>{if(!collected.has(i)){ctx.fillStyle='#e9b439';ctx.fillText('★',s.x-12,s.y+8);}});for(const e of enemies)if(!e.dead){ctx.fillStyle='#c46673';ctx.fillRect(e.x,e.y,e.w,e.h);ctx.fillStyle='#fff';ctx.fillRect(e.x+5,e.y+4,4,4);ctx.fillRect(e.x+15,e.y+4,4,4);}
 for(const [x,color] of [[700,checkpointOn?'#388b72':'#cf8452'],[end+20,'#ce5175']]){ctx.fillStyle=color;ctx.fillRect(x,250,4,60);ctx.beginPath();ctx.moveTo(x+4,250);ctx.lineTo(x+32,261);ctx.lineTo(x+4,272);ctx.fill();}
 ctx.fillStyle='#263c4b';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#fff';ctx.fillRect(p.x+13,p.y+6,4,4);ctx.restore();$('trail-stats').textContent=`${level+1}/12 · ${names[level]} · ${collected.size}/3 ★ · ${elapsed.toFixed(1)}s · ${checkpointOn?'Checkpoint reached':'Find the checkpoint'}`;
 if(paused||won){ctx.fillStyle='#152333aa';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='bold 30px sans-serif';ctx.textAlign='center';ctx.fillText(won?'Flag found!':'Paused',W/2,H/2);ctx.textAlign='left';}}
 function frame(now){if(!active)return;if(last)acc+=Math.min(.1,(now-last)/1000);last=now;while(acc>=1/120){step(1/120);acc-=1/120;}draw();raf=requestAnimationFrame(frame);}
 const control=e=>({'ArrowLeft':'left','a':'left','A':'left','ArrowRight':'right','d':'right','D':'right',' ':'jump','ArrowUp':'jump','w':'jump','W':'jump'}[e.key]);
 const down=e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,select,textarea,button'))return;if(e.key==='Escape'||e.key==='p'||e.key==='P'){e.preventDefault();if(!e.repeat)pause();return;}const k=control(e);if(k&&playing){e.preventDefault();keys.add(k);}},up=e=>keys.delete(control(e));
 const blur=()=>{if(playing&&!paused&&!won)pause();else release();},visibility=()=>{if(document.hidden)blur();};addEventListener('keydown',down);addEventListener('keyup',up);addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);
 document.querySelectorAll('[data-p]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();if(paused||won)return;b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,b.dataset.p);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=e=>pointers.delete(e.pointerId);});
 $('trail-pause').onclick=pause;$('trail-restart').onclick=()=>{sessionStarted=false;start(level);};$('trail-back').onclick=map;$('trail-next').onclick=()=>{sessionStarted=false;start(level+1);};
 clean=()=>{active=false;cancelAnimationFrame(raf);session?.dispose();release();removeEventListener('keydown',down);removeEventListener('keyup',up);removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);};map();save();raf=requestAnimationFrame(frame);
}
