const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const url=require('node:url').pathToFileURL(path.resolve(__dirname,'../index.html')).href;
let source=fs.readFileSync(path.resolve(__dirname,'../adventures.js'),'utf8');
source=source.replace('settle();save();render();\n}',"settle();save();render();window.campQA={get:()=>structuredClone(s)};\n}");
source=source.replace('map();save();raf=requestAnimationFrame(frame);',`map();save();raf=requestAnimationFrame(frame);window.trailQA={start,step,draw,get:()=>({p:{...p},platforms:structuredClone(platforms),stars,enemies:structuredClone(enemies),elapsed,deaths,won,paused,checkpoint,checkpointOn,collected:[...collected],saved:structuredClone(saved),level}),key:(k,v)=>v?keys.add(k):keys.delete(k),place:(x,y,vy=0)=>{p.x=x;p.y=y;p.vy=vy;p.vx=0;p.on=null;},spawn};`);
(async()=>{const browser=await chromium.launch({headless:true}),p=await browser.newPage({viewport:{width:1100,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/adventures.js',r=>r.fulfill({contentType:'text/javascript',body:source}));await p.goto(url);await p.clock.install();await p.clock.pauseAt(new Date());
const camp=()=>p.evaluate(()=>campQA.get()),trail=()=>p.evaluate(()=>trailQA.get());
await p.evaluate(()=>play('clicker'));assert.ok(await p.locator('#upgrade').isDisabled());assert.ok(await p.locator('#helper').isDisabled());
for(let i=0;i<15;i++)await p.locator('#coin').click();await p.locator('#upgrade').click();assert.equal((await camp()).power,2);assert.equal((await camp()).coins,0);
for(let i=0;i<18;i++)await p.locator('#coin').click();await p.locator('#helper').click();assert.equal((await camp()).helpers,1);await p.clock.runFor(5000);assert.equal(Math.floor((await camp()).coins),6);
assert.ok(await p.locator('#quests button').first().isEnabled());await p.locator('#quests button').first().click();assert.equal(Math.floor((await camp()).coins),56);assert.ok(await p.locator('#quests button').first().isDisabled());
await p.locator('#trip').click();assert.ok(await p.locator('#trip').isDisabled());assert.equal((await camp()).trip.region,0);await p.clock.runFor(30000);assert.equal((await camp()).trips,1);assert.equal((await camp()).trip,null);assert.equal(Math.floor((await camp()).coins),131);
await p.clock.runFor(10000);assert.ok(await p.locator('#camp-bonus').isVisible());const b=(await camp()).coins;await p.locator('#camp-bonus').click();assert.equal((await camp()).coins,b+50);assert.ok(await p.locator('#camp-bonus').isHidden());
await p.evaluate(()=>home());await p.clock.setSystemTime(new Date(Date.now()+6*3600000));await p.evaluate(()=>play('clicker'));assert.equal(Math.floor((await camp()).coins),Math.floor(b+50+14400));assert.match(await p.locator('#camp-note').textContent(),/Welcome back/);
await p.locator('#region').click();assert.equal((await camp()).region,1);await p.locator('#trip').click();await p.clock.runFor(60000);assert.equal((await camp()).trips,2);await p.locator('#region').click();assert.equal((await camp()).region,2);assert.ok(await p.locator('#region').isDisabled());await p.locator('#trip').click();await p.clock.runFor(90000);assert.equal((await camp()).trips,3);
await p.locator('#quests button').nth(2).click();await p.locator('#quests button').nth(3).click();assert.deepEqual((await camp()).quests,[0,2,3]);await p.reload();await p.evaluate(()=>play('clicker'));assert.equal((await camp()).region,2);assert.equal((await camp()).trips,3);
// All journal rewards, a saved expedition returning once, and the scoped reset confirmation.
await p.locator('#helper').click();await p.locator('#helper').click();assert.equal((await camp()).helpers,3);await p.locator('#quests button').nth(1).click();assert.equal((await camp()).quests.length,4);
await p.locator('#trip').click();const pending=await camp();await p.evaluate(()=>home());await p.clock.runFor(90000);await p.reload();await p.evaluate(()=>play('clicker'));assert.equal((await camp()).trips,pending.trips+1);assert.equal(Math.floor((await camp()).coins),Math.floor(pending.coins+810+1350));const returned=await camp();await p.reload();await p.evaluate(()=>play('clicker'));assert.equal((await camp()).trips,returned.trips);assert.equal((await camp()).coins,returned.coins);
await p.locator('summary').click();p.once('dialog',d=>d.dismiss());await p.locator('#camp-reset').click();assert.equal((await camp()).helpers,3);p.once('dialog',d=>d.accept());await p.locator('#camp-reset').click();assert.equal((await camp()).power,1);assert.equal((await camp()).coins,0);assert.equal((await camp()).helpers,0);await p.clock.runFor(3000);assert.equal((await camp()).coins,0,'Old camp timers are removed on reset');
// All twelve courses are traversed through the actual movement/collision loop. No positions are changed.
await p.evaluate(()=>play('platform'));assert.equal(await p.locator('[data-level]:enabled').count(),1);await p.locator('[data-level="0"]').click();await p.keyboard.down(' ');await p.clock.runFor(100);await p.keyboard.up(' ');assert.ok((await trail()).p.y<270,'The first jump responds immediately');await p.locator('#trail-back').click();
for(let i=0;i<12;i++){
 await p.locator(`[data-level="${i}"]`).click();
 const result=await p.evaluate(()=>{const q=trailQA;q.key('right',true);for(let n=0;n<120*45;n++){const s=q.get();if(s.won)break;q.key('right',true);const floor=s.platforms.find(a=>a.id===s.p.on);q.key('jump',s.p.vy<0||!!floor&&((floor.x+floor.w-s.p.x-s.p.w<60||s.enemies.some(e=>!e.dead&&e.x-s.p.x<95&&e.x-s.p.x> -15))));q.step(1/120);}q.draw();return q.get();});
 console.log('course',i+1,'won',result.won,'x',result.p.x,'retries',result.deaths);
 assert.equal(result.won,true,`Course ${i+1} is traversable`);assert.ok(result.elapsed>0);assert.equal(result.saved.levels[i].done,true);await p.locator('#trail-back').click();
}
await p.reload();await p.evaluate(()=>play('platform'));assert.equal(await p.locator('[data-level]:enabled').count(),12);
// Individual collision boundaries, collectibles, death/checkpoint, pause and touch.
await p.locator('[data-level="6"]').click();await p.keyboard.down('ArrowRight');await p.clock.runFor(300);await p.keyboard.up('ArrowRight');const moved=(await trail()).p.x;assert.ok(moved>40);
await p.locator('#trail-pause').click();const before=await trail();await p.clock.runFor(2000);assert.equal((await trail()).elapsed,before.elapsed);assert.equal((await trail()).p.x,before.p.x);await p.locator('#trail-pause').click();
await p.evaluate(()=>{trailQA.place(695,279);trailQA.step(1/120);});assert.equal((await trail()).checkpointOn,true);await p.evaluate(()=>{trailQA.place(850,440);trailQA.step(1/120);});assert.equal((await trail()).p.x,690);
for(let i=0;i<3;i++)await p.evaluate(i=>{const a=trailQA.get().stars[i];trailQA.place(a.x,a.y);trailQA.step(1/120);},i);assert.equal((await trail()).collected.length,3);
await p.evaluate(()=>{trailQA.place(1511,280);trailQA.step(1/120);});assert.equal((await trail()).won,true);assert.deepEqual((await trail()).saved.levels[6].stars,[0,1,2]);
await p.locator('#trail-restart').click();await p.keyboard.down('ArrowRight');await p.clock.runFor(100);await p.keyboard.up('ArrowRight');await p.evaluate(()=>dispatchEvent(new Event('blur')));assert.equal((await trail()).paused,true);await p.locator('#trail-pause').click();
await p.locator('[data-p="right"]').dispatchEvent('pointerdown',{pointerId:1});await p.clock.runFor(200);await p.locator('[data-p="right"]').dispatchEvent('pointercancel',{pointerId:1});const tx=(await trail()).p.x;await p.clock.runFor(400);assert.ok((await trail()).p.x-tx<25,'Touch cancellation releases control');
const touch=await p.context().newCDPSession(p);const rb=await p.locator('[data-p="right"]').boundingBox(),jb=await p.locator('[data-p="jump"]').boundingBox();const touchX=(await trail()).p.x;await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:rb.x+rb.width/2,y:rb.y+rb.height/2,id:1},{x:jb.x+jb.width/2,y:jb.y+jb.height/2,id:2}]});await p.clock.runFor(150);assert.ok((await trail()).p.x>touchX);await touch.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await p.clock.runFor(300);const stopX=(await trail()).p.x;await p.clock.runFor(300);assert.equal((await trail()).p.x,stopX,'Real touch cancellation clears both controls');await touch.detach();
// Spring launch, moving-platform carrying, crumble recovery, enemy stomp and side damage.
await p.evaluate(()=>{trailQA.start(10);trailQA.key('right',true);trailQA.step(1/120);trailQA.key('right',false);const a=trailQA.get().platforms.find(a=>a.type==='spring');trailQA.place(a.x+20,a.y-31,180);trailQA.step(1/120);});assert.ok((await trail()).p.vy< -500,'Spring launches the player');
await p.evaluate(()=>{const a=trailQA.get().platforms.find(a=>a.type==='moving');trailQA.place(a.x+20,a.y-31,180);trailQA.step(1/120);});const mx=(await trail()).p.x;await p.evaluate(()=>{for(let i=0;i<15;i++)trailQA.step(1/120);});assert.notEqual((await trail()).p.x,mx,'Moving platform carries its passenger');
await p.evaluate(()=>{const a=trailQA.get().platforms.find(a=>a.type==='crumble');trailQA.place(a.x+20,a.y-31,180);trailQA.step(1/120);for(let i=0;i<80;i++)trailQA.step(1/120);});assert.ok((await trail()).platforms.some(a=>a.gone>0),'Crumbling platform disappears');await p.evaluate(()=>{for(let i=0;i<360;i++)trailQA.step(1/120);});assert.ok((await trail()).platforms.every(a=>a.gone===0),'Crumbling platforms return');
await p.evaluate(()=>{trailQA.start(3);trailQA.key('right',true);trailQA.step(1/120);trailQA.key('right',false);const e=trailQA.get().enemies[0];trailQA.place(e.x,e.y-31,200);trailQA.step(1/120);});assert.equal((await trail()).enemies[0].dead,true,'Landing from above defeats an enemy');
await p.evaluate(()=>{trailQA.start(3);trailQA.key('right',true);trailQA.step(1/120);trailQA.key('right',false);const e=trailQA.get().enemies[0];trailQA.place(e.x,e.y);trailQA.step(1/120);});assert.equal((await trail()).deaths,1,'Side contact causes a retry');
// Short taps produce a lower jump than holding, and the edge-jump grace period works.
const jumpHeight=async hold=>p.evaluate(hold=>{trailQA.start(0);for(let i=0;i<30;i++)trailQA.step(1/120);trailQA.key('right',true);trailQA.step(1/120);trailQA.key('right',false);for(let i=0;i<30;i++)trailQA.step(1/120);trailQA.key('jump',true);let min=999;for(let i=0;i<80;i++){if(i===2&&!hold)trailQA.key('jump',false);trailQA.step(1/120);min=Math.min(min,trailQA.get().p.y);}return min;},hold);
assert.ok(await jumpHeight(true)<await jumpHeight(false)-25,'Holding jump gives useful height control');
await p.evaluate(()=>{trailQA.start(0);trailQA.key('right',true);trailQA.step(1/120);trailQA.key('right',false);trailQA.place(325,279,180);trailQA.step(1/120);trailQA.step(1/120);trailQA.place(334,280);trailQA.step(1/120);trailQA.key('jump',true);trailQA.step(1/120);});assert.ok((await trail()).p.vy<0,'Jump remains available just past a ledge');
// Each star is reached by a jump from an approach on the ground, without placing the player onto the star.
for(let i=0;i<12;i++){const count=await p.evaluate(i=>{trailQA.start(i);trailQA.key('right',true);trailQA.step(1/120);trailQA.key('right',false);for(const a of trailQA.get().stars){trailQA.place(a.x-100,280);trailQA.key('jump',false);for(let n=0;n<4;n++)trailQA.step(1/120);trailQA.key('jump',true);trailQA.key('right',true);for(let n=0;n<110;n++){if(trailQA.get().p.x>=a.x-12)trailQA.key('right',false);trailQA.step(1/120);}trailQA.key('jump',false);trailQA.key('right',false);}return trailQA.get().collected.length;},i);assert.equal(count,3,`All three stars on level ${i+1} are reachable`);}
for(const width of [1100,375,320]){await p.setViewportSize({width,height:950});for(const game of ['clicker','platform']){await p.evaluate(g=>play(g),game);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),game+' fits mobile');await p.screenshot({path:`/tmp/adventure-${game}-${width}.png`,fullPage:true});if(game==='platform'){await p.locator('[data-level="0"]').click();await p.screenshot({path:`/tmp/adventure-course-${width}.png`,fullPage:true});}}}
await p.evaluate(()=>home());await p.clock.runFor(10000);assert.deepEqual(errors,[]);
// New daily goals count actual taps and a real level finish, with exact thresholds.
for(const id of ['camp-fifty','trail-flag']){const day=await p.evaluate(id=>Array.from({length:110},(_,i)=>new Date(Date.UTC(2026,8,10+i)).toISOString().slice(0,10)).find(d=>DailyChallenges.set(d).some(g=>g.id===id)),id);await p.clock.setSystemTime(new Date(day+'T10:00:00Z'));
if(id==='camp-fifty'){await p.evaluate(()=>play('clicker'));await p.evaluate(()=>{for(let i=0;i<49;i++)document.querySelector('#coin').click();});assert.equal(await p.evaluate(d=>DailyChallenges.getState().days[d]['camp-fifty'],day),49);await p.locator('#coin').click();assert.equal(await p.evaluate(d=>DailyChallenges.getState().days[d]['camp-fifty'],day),50);}
else{await p.evaluate(()=>play('platform'));await p.locator('[data-level="0"]').click();await p.evaluate(()=>{trailQA.place(1509,280);trailQA.key('right',true);for(let i=0;i<15;i++)trailQA.step(1/120);});assert.equal(await p.evaluate(d=>DailyChallenges.getState().days[d]['trail-flag'],day),1);}}
// Defensive saves and denied storage.
for(const value of ['{bad',JSON.stringify({power:-1,coins:'oops',helpers:Infinity,trip:{end:'oops'},levels:[{done:true,stars:'bad'}]})]){await p.evaluate(v=>{localStorage.setItem('shelf-camp-v1',v);localStorage.setItem('shelf-platform-v1',v);},value);await p.evaluate(()=>play('clicker'));assert.equal((await camp()).power,1);await p.evaluate(()=>play('platform'));}
const q=await browser.newPage();await q.addInitScript(()=>{Storage.prototype.getItem=()=>{throw Error('blocked')};Storage.prototype.setItem=()=>{throw Error('blocked')};});await q.goto(url);await q.evaluate(()=>play('clicker'));await q.locator('#coin').click();assert.match(await q.locator('#camp-storage').textContent(),/unavailable/);await q.evaluate(()=>play('platform'));assert.match(await q.locator('#trail-storage').textContent(),/unavailable/);await q.close();
assert.deepEqual(errors,[]);await browser.close();console.log('PASS adventure economy, expeditions, offline cap, saves, quests, all 12 courses, controls, checkpoints, stars, pause, responsive layouts and cleanup.');
})().catch(e=>{console.error(e);process.exit(1)});
