const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({headless:true}),p=await browser.newPage({viewport:{width:1100,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('node:url').pathToFileURL(path.join(root,'index.html')).href);await p.clock.install();
const seed=async(n,answer,stats={})=>p.evaluate(({n,answer,stats})=>{localStorage.setItem(`word-vault-${n}`,JSON.stringify({wins:0,played:0,streak:0,best:0,...stats,round:{answer,guesses:[],status:'playing'}}));},{n,answer,stats});
const guess=async(w)=>{await p.keyboard.type(w);await p.keyboard.press('Enter');await p.clock.runFor(1000);};
assert.deepEqual(await p.evaluate(()=>gradeVault('ALLEY','APPLE')),['correct','present','absent','present','absent']);assert.deepEqual(await p.evaluate(()=>gradeVault('EERIE','SHEEP')),['present','present','absent','absent','absent']);
await seed(5,'APPLE');await p.evaluate(()=>play('word'));assert.equal(await p.locator('.vault-tile').count(),30);await p.keyboard.type('ab');await p.keyboard.press('Enter');assert.ok((await p.textContent('#vault-notice')).includes('5 letters'));await p.keyboard.press('Backspace');await p.keyboard.press('Backspace');await guess('zzzzz');assert.ok((await p.textContent('#vault-notice')).includes('not recognised'));assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('word-vault-5')).round.guesses.length),0);
for(let i=0;i<5;i++)await p.keyboard.press('Backspace');await guess('alley');assert.equal(await p.locator('.vault-row').first().locator('.correct').count(),1);assert.equal(await p.locator('[data-key="L"]').getAttribute('class'),'present ');await guess('alley');assert.ok((await p.textContent('#vault-notice')).includes('already'));for(let i=0;i<5;i++)await p.keyboard.press('Backspace');await guess('apple');assert.equal(await p.textContent('#vault-state'),'ACCESS GRANTED');assert.equal(await p.textContent('#vault-streak'),'1');await p.keyboard.press('Enter');assert.equal(await p.textContent('#vault-wins'),'1');
await p.reload();await p.evaluate(()=>play('word'));assert.equal(await p.textContent('#vault-state'),'ACCESS GRANTED');await p.click('#vault-new');assert.equal(await p.locator('.vault-tile.filled').count(),0);
await seed(4,'MOON');await seed(6,'PLANET');await p.selectOption('#vault-size','4');assert.equal(await p.locator('.vault-tile').count(),24);for(const key of ['M','O','O','N','↵'])await p.locator(`[data-key="${key}"]`).click();await p.clock.runFor(1000);assert.equal(await p.textContent('#vault-state'),'ACCESS GRANTED');await p.selectOption('#vault-size','6');assert.equal(await p.locator('.vault-tile').count(),36);await guess('planet');assert.equal(await p.textContent('#vault-state'),'ACCESS GRANTED');
await seed(5,'APPLE',{wins:3,played:3,streak:3,best:3});await p.evaluate(()=>play('word'));for(const w of ['crane','ghost','music','orbit','water','zebra'])await guess(w);assert.equal(await p.textContent('#vault-state'),'ACCESS DENIED');assert.ok((await p.textContent('#vault-notice')).includes('APPLE'));assert.equal(await p.textContent('#vault-streak'),'0');assert.equal(await p.textContent('#vault-best'),'3');
await seed(5,'APPLE',{wins:2,played:2,streak:2,best:2});await p.evaluate(()=>play('word'));await guess('crane');await p.evaluate(()=>home());await p.evaluate(()=>play('word'));assert.equal(await p.locator('.vault-row').first().locator('.filled').count(),5);await p.click('#vault-new');assert.equal(await p.textContent('#vault-streak'),'0');
// Animation input lock and navigation cleanup; accepted results persist immediately.
await seed(5,'APPLE');await p.evaluate(()=>play('word'));await p.keyboard.type('apple');await p.keyboard.press('Enter');await p.keyboard.type('xxxxx');assert.equal(await p.textContent('#vault-state'),'DECODING…');await p.evaluate(()=>home());await p.clock.runFor(1500);assert.equal(await p.locator('.hero').count(),1);await p.evaluate(()=>play('word'));assert.equal(await p.textContent('#vault-state'),'ACCESS GRANTED');
const out=fs.mkdtempSync('/tmp/vault-tests-');for(const width of [1100,375]){await p.setViewportSize({width,height:1100});await seed(5,'APPLE');await p.evaluate(()=>play('word'));await guess('alley');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(out,`vault-${width}.png`),fullPage:true});for(const n of ['4','6']){await p.selectOption('#vault-size',n);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}}
// Storage failure must leave a playable session.
await p.evaluate(()=>{Storage.prototype.setItem=()=>{throw Error('blocked')};Storage.prototype.getItem=()=>{throw Error('blocked')};play('word');});assert.equal(await p.locator('.vault-tile').count(),30);await guess('crane');assert.equal(await p.locator('.vault-row').first().locator('.filled').count(),5);assert.ok((await p.textContent('#vault-save-note')).includes('unavailable'));assert.deepEqual(errors,[]);await browser.close();console.log('PASS: repeated-letter scoring, dictionary validation, duplicate guesses, keyboard/touch, all lengths, win/loss, saved streaks/progress, abandonment, animation lock, cleanup, blocked storage and responsive layouts. Screenshots:',out);
})().catch(e=>{console.error(e);process.exit(1)});
